"""initial schema

Revision ID: ba78cdaa98bf
Revises:
Create Date: 2026-07-22 12:44:28.139893

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba78cdaa98bf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=50), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_runs_job_name_started_at", "job_runs", ["job_name", "started_at"], unique=False
    )
    op.create_table(
        "stocks",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("industry", sa.String(length=50), nullable=True),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "alert_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("alert_type", sa.String(length=20), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_settings_symbol", "alert_settings", ["symbol"], unique=False)
    op.create_table(
        "daily_prices",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_index("ix_daily_prices_date", "daily_prices", ["date"], unique=False)
    op.create_table(
        "financial_statements",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("eps", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("revenue", sa.BigInteger(), nullable=True),
        sa.Column("roe", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "period_end"),
    )
    op.create_table(
        "institutional_trades",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("foreign_net", sa.BigInteger(), nullable=False),
        sa.Column("trust_net", sa.BigInteger(), nullable=False),
        sa.Column("dealer_net", sa.BigInteger(), nullable=False),
        sa.Column("total_net", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_index("ix_institutional_trades_date", "institutional_trades", ["date"], unique=False)
    op.create_table(
        "major_holders",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("holder_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("holder_count", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_table(
        "margin_trading",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("margin_balance", sa.BigInteger(), nullable=False),
        sa.Column("margin_change", sa.BigInteger(), nullable=False),
        sa.Column("short_balance", sa.BigInteger(), nullable=False),
        sa.Column("short_change", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_index("ix_margin_trading_date", "margin_trading", ["date"], unique=False)
    op.create_table(
        "screener_results",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("matched_rules", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("date", "symbol"),
    )
    op.create_table(
        "technical_indicators",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ma5", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ma10", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ma20", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ma60", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("rsi14", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("kd_k", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("kd_d", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("macd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("macd_signal", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("macd_hist", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("bb_upper", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("bb_middle", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("bb_lower", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_index("ix_technical_indicators_date", "technical_indicators", ["date"], unique=False)
    op.create_table(
        "valuations",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("pe_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("pb_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol", "date"),
    )
    op.create_index("ix_valuations_date", "valuations", ["date"], unique=False)
    op.create_table(
        "watchlist",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist")
    op.drop_index("ix_valuations_date", table_name="valuations")
    op.drop_table("valuations")
    op.drop_index("ix_technical_indicators_date", table_name="technical_indicators")
    op.drop_table("technical_indicators")
    op.drop_table("screener_results")
    op.drop_index("ix_margin_trading_date", table_name="margin_trading")
    op.drop_table("margin_trading")
    op.drop_table("major_holders")
    op.drop_index("ix_institutional_trades_date", table_name="institutional_trades")
    op.drop_table("institutional_trades")
    op.drop_table("financial_statements")
    op.drop_index("ix_daily_prices_date", table_name="daily_prices")
    op.drop_table("daily_prices")
    op.drop_index("ix_alert_settings_symbol", table_name="alert_settings")
    op.drop_table("alert_settings")
    op.drop_table("stocks")
    op.drop_index("ix_job_runs_job_name_started_at", table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
